### ISSUE TITLE
 并没有优化啊

### ISSUE THREAD

**Issue by lfkdsk** [icela/StudioVSEclipse#1]
试试ObjectPool或者那个啥group

**Comment by ice1000** [comment]
。。。我之前寄希望于JVM的GC，因为我生成的对象全是局部变量。。
在心理上我以为JVM会回收。。。后来发现我忽略了他们依旧存在于Engine中。。。
:joy: 我试试OP吧，之前在阅读源代码的时候就看到了，不过没仔细看看。。
我整理了下它的代码风格。。至少我觉得那样看着好些

**Comment by ice1000** [comment]
我优化了敌军了。。 :smile:

**Comment by lfkdsk** [comment]
其实还是设计比较有意思，实际的代码就不会太好玩了⊙▽⊙。

**Comment by ice1000** [comment]
诶？我觉得都挺有意思啊 :joy: 难道注定搬砖一生

**Comment by lfkdsk** [comment]
@ice1000 你要没啥写的可以给jw写包啊＝－＝(鬼畜的笑)
