### ISSUE TITLE
 ‭

### ISSUE THREAD

**Issue by zhangnew** [icela/StudioVSEclipse#2]

**Comment by ice1000** [comment]
卧槽，真的？我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by ice1000** [comment]
卧槽，真的？
那我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by ice1000** [comment]
卧槽，真的？
那我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by ice1000** [comment]
卧槽，真的？
那我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by ice1000** [comment]
卧槽，真的？
那我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by ice1000** [comment]
卧槽，真的？
那我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by ice1000** [comment]
卧槽，真的？
那我回去调试一下。
本来是有一个屏幕旋转的问题的，不过上周我的Genymotion老是连不上，手机也被收了，这周末我回去重新调一下。 :joy:

**Comment by lfkdsk** [comment]
ahhhhh

**Comment by ice1000** [comment]
@lfkdsk 我又看了一下，总感觉就只设置了一次屏幕的方向啊，你再看看还有没有什么别的可能性？

**Comment by zhangnew** [comment]
也可能是巧合吧，虽然我手机很少发生这种情况

**Comment by lfkdsk** [comment]
@ice1000 那个我都修好了，是因为我默认设为横屏，然后这就会出现系统竖屏－> 我设为横屏－>你又设为竖屏，短时间三次切换出的bug，现在已经没有问题了。

**Comment by ice1000** [comment]
问题一：也就是说我现在这个版本要是编译出来的话是大丈夫的对吧？ :joy: 
问题二：我现在是搞了个Activity先启动，然后按下开始游戏之后跳转到Game类没问题吧？ 
@lfkdsk

**Comment by ice1000** [comment]
@zhangnew 你编译一下嘛。。。  :astonished: 
所以说对于游戏本身有没有啥想法？打到后期是不是很蛋疼？
还有，我还是个青春少年你就叫我大兄弟让我情何以堪 :disappointed:

**Comment by lfkdsk** [comment]
嗯，跳转什么的肯定没问题啊。

**Comment by zhangnew** [comment]
@ice1000 小兄弟啊，我觉得如果不是无聊到极致，不会有人玩这个游戏的。游戏本身太粗糙，槽点太多，我不想说啥了，我对一个 deamo 能有什么想法。。。

**Comment by ice1000** [comment]
@zhangnew 首先，是demo不是deamo，GitHub已经有拼写检查了，不知道你为什么还打错。
然后，我自己就在玩，而且我并不无聊。
你也真是无聊到极致了

**Comment by ice1000** [comment]
。。不过谢谢你的意见
